[[commands]]
name = "cat"
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
name = "cd"
allow_positional = true
positional_path_from = 0

[[commands]]
name = "echo"
allow_any = true

[[commands]]
name = "expr"
allow_any = true

[[commands]]
name = "false"
allow_any = true

[[commands]]
name = "grep"
allow_any = true
allow_positional = true
positional_path_from = 1

[[commands]]
name = "head"
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
name = "id"
allow_any = true

[[commands]]
name = "ls"
allow_any = true
allow_positional = true
positional_path_from = 0
flags = [
  { name = "-a", arg = "none" },
  { name = "-l", arg = "none" },
  { name = "-n", arg = "none" },
  { name = "--color", arg = "optional" },
]

[[commands]]
name = "nl"
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
name = "pwd"
allow_any = true

[[commands]]
name = "tail"
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
name = "true"
allow_any = true

[[commands]]
name = "uname"
allow_any = true

[[commands]]
name = "uniq"
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
name = "wc"
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
name = "which"
allow_any = true

[[commands]]
name = "whoami"
allow_any = true

[[commands]]
command = ["git", "branch"]
allow_any = true

[[commands]]
command = ["git", "status"]
allow_any = true

[[commands]]
command = ["git", "log"]
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
command = ["git", "diff"]
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
command = ["git", "show"]
allow_any = true
allow_positional = true
positional_path_from = 0

[[commands]]
command = ["git", "commit"]
flags = [{ name = "--dry-run", arg = "none" }]

[[commands]]
command = ["cargo", "check"]
allow_any = true
