[package]
name = "coco-tui"
version.workspace = true
edition.workspace = true
build = "../../build.rs"

[[bin]]
name = "coco"
path = "src/main.rs"

# Terminal UI dependencies for building console interfaces
[dependencies]
# Core
code-combo = { path = "../.." }
coco-macro = { path = "../coco-macro/" }
anthropic = { path = "../anthropic" }

# CLI
clap.workspace = true

# Error handling
snafu = { workspace = true, features = ["backtrace"] }

# Terminal backend and input handling
crossterm = { version = "0.28.1", features = ["event-stream"] }

# Async utilities
tokio.workspace = true
tokio-util.workspace = true
futures = "0.3.31"

# Terminal UI framework
ratatui = { version = "0.29.0", features = [
  "serde",
  "unstable-rendered-line-info",
  "unstable-widget-ref",
] }
code-highlight = { path = "../code-highlight" }
ansi-to-tui = "7.0.0"
tui-textarea = "0.7.0"

# Logging
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true

# Serialization and data handling
serde.workspace = true
serde_json.workspace = true

# Builder
bon.workspace = true

# Others
ctor.workspace = true
lazy_static.workspace = true
bitflags = "2.10.0"
indoc.workspace = true
time = { workspace = true, features = [
  "macros",
  "serde",
  "local-offset",
  "formatting",
  "parsing",
] }

[dev-dependencies]

[build-dependencies]
time = { workspace = true, features = ["formatting"] }
