[[model_presets]]
model = "deepseek-chat"
disable_tool_choice = true
tool_choice_fallback = true
combo_reply_retries = 1
context_window = 128000
can_reason = false
max_tokens = 4000

[[model_presets]]
model = "deepseek-reasoner"
disable_tool_choice = true
tool_choice_fallback = true
combo_reply_retries = 1
context_window = 128000
can_reason = true
max_tokens = 32000

[[model_presets]]
model = "kimi-k2-thinking"
include_reasoning_content = true
offload_combo_reply = true
combo_reply_retries = 1
temperature = 1.0
max_tokens = 16000

[[model_presets]]
model = "glm-4.7"
max_tokens = 131072
context_window = 204800
can_reason = true
include_reasoning_content = true
offload_combo_reply = true
combo_reply_retries = 1

[[model_presets]]
model = "glm-4.6"
max_tokens = 131072
context_window = 204800
can_reason = true
offload_combo_reply = true
combo_reply_retries = 1

[[model_presets]]
model = "glm-4.5"
max_tokens = 98304
context_window = 131072
can_reason = true
offload_combo_reply = true
combo_reply_retries = 1

[[model_presets]]
model = "glm-4.5-air"
max_tokens = 98304
context_window = 131072
can_reason = true
offload_combo_reply = true
combo_reply_retries = 1
